In [2]:
import numpy as np
import math

In [3]:
np.e

2.718281828459045

In [6]:
(math.pow(2.718281828459045,0.2867))

1.3320245461647273

In [5]:
np.log(math.pow(2.718281828459045,0.2867))

np.float64(0.2867)

In [10]:
data1=np.random.randint(0,10,(3,3))
data2=np.random.randint(0,10,(3,3))
data1

array([[5, 1, 6],
       [6, 0, 7],
       [3, 0, 9]])

In [11]:
data2

array([[3, 9, 7],
       [2, 1, 0],
       [7, 6, 5]])

In [12]:
data1+data2

array([[ 8, 10, 13],
       [ 8,  1,  7],
       [10,  6, 14]])

In [14]:
np.add(data1,data2)

array([[ 8, 10, 13],
       [ 8,  1,  7],
       [10,  6, 14]])

In [17]:
np.subtract(data1,data2)

array([[ 2, -8, -1],
       [ 4, -1,  7],
       [-4, -6,  4]])

In [18]:
np.multiply(data1,data2)

array([[15,  9, 42],
       [12,  0,  0],
       [21,  0, 45]])

In [19]:
np.divide(data1,data2)

/tmp/ipython-input-18017515.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(data1,data2)


array([[1.66666667, 0.11111111, 0.85714286],
       [3.        , 0.        ,        inf],
       [0.42857143, 0.        , 1.8       ]])

In [20]:
data=np.random.randint(0,10,10)
data

array([3, 9, 5, 5, 3, 1, 8, 0, 1, 4])

In [21]:
data>5

array([False,  True, False, False, False, False,  True, False, False,
       False])

In [23]:
data[data>5]

array([9, 8])

In [24]:
marks=np.random.randint(0,100,20)
marks

array([23, 44, 84, 48, 27,  4, 19, 30, 93, 37, 44, 95, 80, 33, 26, 67, 70,
       37, 36, 27])

In [25]:
marks[marks>50]

array([84, 93, 95, 80, 67, 70])

In [26]:
marks[marks<=50]

array([23, 44, 48, 27,  4, 19, 30, 37, 44, 33, 26, 37, 36, 27])

In [29]:
marks[marks>marks.mean()]

array([84, 48, 93, 95, 80, 67, 70])

In [31]:
marks[marks>np.mean(marks)]

array([84, 48, 93, 95, 80, 67, 70])

In [34]:
data=np.random.randint(0,10,(3,3))
data

array([[6, 7, 4],
       [7, 3, 3],
       [0, 6, 3]])

In [35]:
data.ravel()

array([6, 7, 4, 7, 3, 3, 0, 6, 3])

In [37]:
data

array([[6, 7, 4],
       [7, 3, 3],
       [0, 6, 3]])

In [38]:
data.T

array([[6, 7, 0],
       [7, 3, 6],
       [4, 3, 3]])

In [46]:
data=np.random.randint(0,10,20)
data.reshape(4,5)

array([[4, 8, 2, 3, 6],
       [7, 2, 6, 9, 0],
       [1, 7, 3, 6, 6],
       [1, 2, 6, 1, 0]])

In [41]:
data.reshape(4,5)

array([[6, 9, 8, 8, 1],
       [5, 4, 6, 1, 1],
       [1, 6, 3, 2, 4],
       [3, 4, 9, 2, 1]])

In [47]:
data1=np.random.randint(0,10,(3,3))
data2=np.random.randint(0,10,(3,3))

In [48]:
data1

array([[4, 3, 5],
       [3, 4, 7],
       [8, 7, 6]])

In [49]:
data2

array([[7, 8, 0],
       [8, 3, 2],
       [0, 3, 9]])

In [51]:
np.hstack([data1,data2])

array([[4, 3, 5, 7, 8, 0],
       [3, 4, 7, 8, 3, 2],
       [8, 7, 6, 0, 3, 9]])

In [52]:
np.vstack([data1,data2])

array([[4, 3, 5],
       [3, 4, 7],
       [8, 7, 6],
       [7, 8, 0],
       [8, 3, 2],
       [0, 3, 9]])

In [57]:
data=np.random.randint(0,10,10)
np.split(data,2) #it divide array in 2 equal parts because we write 2 in bracket

[array([7, 3, 1, 0, 9]), array([0, 1, 0, 7, 4])]

In [72]:
matrix = np.array([[1,2,3,4],
                [5,6,7,8]])
matrix


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.hsplit(matrix,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [78]:
np.vsplit(matrix,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [82]:
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,14,16]])

In [91]:
np.vsplit(matrix,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 14, 16]])]