In [ ]:
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[41, 39, 65, 36, 13],
       [29, 94, 76, 68, 12],
       [25, 60, 20, 56, 89],
       [99, 62,  0, 44, 25],
       [ 0, 77, 22, 74, 67]])

In [ ]:
type(data)

numpy.ndarray

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
type(np.array([1,2,3]))

numpy.ndarray

In [ ]:
print(data)
print(" ")
print(data[-3:-1,-3:-1])

[[41 39 65 36 13]
 [29 94 76 68 12]
 [25 60 20 56 89]
 [99 62  0 44 25]
 [ 0 77 22 74 67]]
 
[[20 56]
 [ 0 44]]


In [ ]:
data[-2:-1,-2:-1]

array([[44]])

In [ ]:
x=[1,2,3]
print(type(x))
y=np.array([1,2,3])
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,6.0,"data"])

In [ ]:
x

[1, 2, 3, 6.0, 'data']

In [ ]:
y

array(['1', '2', '3', '6.0', 'data'], dtype='<U32')

In [ ]:
###random family function


In [ ]:
np.random.randint(0,100,5)

array([ 3, 44, 28, 57, 97])

In [ ]:
np.random.randint(0,100,(5,5))

array([[80, 56, 27, 57, 52],
       [43, 12,  9, 65, 47],
       [91, 82, 67, 36, 89],
       [23,  0, 65, 45, 52],
       [14, 23, 66, 56, 92]])

In [ ]:
np.random.rand(4,5)

array([[0.3576984 , 0.82590179, 0.63893517, 0.04057985, 0.31379757],
       [0.7062431 , 0.63000639, 0.18362643, 0.89569918, 0.20140966],
       [0.56575431, 0.6691383 , 0.33017396, 0.24696836, 0.98921492],
       [0.8717891 , 0.35515318, 0.40342044, 0.90207036, 0.65277615]])

In [ ]:
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])