In [3]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[4, 6, 9],
       [8, 2, 9],
       [4, 8, 5]])

In [14]:
np.random.randn(30,30).mean()

np.float64(-0.022731195795212343)

In [15]:
# np.mean
# std
# var
# np.median

In [16]:
np.std(data)

np.float64(2.3778816176702997)

In [17]:
np.var(data)


np.float64(5.65432098765432)

In [18]:
np.mean(data)

np.float64(6.111111111111111)

In [20]:
np.median(data)

np.float64(6.0)

In [24]:
data= np.random.randint(0,100,10)
data

array([94, 72, 80, 53, 11, 59, 29, 33, 68, 16])

In [27]:
range = data.min(),data.max()
range

(np.int64(11), np.int64(94))

In [29]:
import numpy as np
data = np.random.randint(0,5,(3,3))
data

array([[4, 1, 4],
       [3, 1, 2],
       [3, 3, 2]])

In [32]:
data.sum()

np.int64(23)

In [39]:
data.sum(axis=1)

array([9, 6, 8])

In [38]:
data.sum(axis=0)

array([10,  5,  8])

In [40]:
data.max(axis=0)

array([4, 3, 4])

In [41]:
data.sum(axis=1)

array([9, 6, 8])

In [42]:
data

array([[4, 1, 4],
       [3, 1, 2],
       [3, 3, 2]])

In [45]:
data.max(axis=0)

array([4, 3, 4])

In [46]:
data.min(axis=1)

array([1, 1, 2])

In [47]:
data

array([[4, 1, 4],
       [3, 1, 2],
       [3, 3, 2]])

In [48]:
data[0:2,0:2].max()

np.int64(4)

In [52]:
data=np.random.randint(0,10,10)
data

array([7, 8, 7, 0, 8, 2, 7, 6, 7, 4])

In [53]:
data.min()

np.int64(0)

In [54]:
data.argmin()

np.int64(3)

In [57]:
data=np.random.randint(0,100,(3,3))
data

array([[77,  8, 94],
       [62, 99, 77],
       [48, 30, 17]])

In [58]:
data.argmin(axis=1)

array([1, 0, 2])