In [1]:
import numpy as np


In [4]:
np.loadtxt("/content/sample.csv",delimiter=",",skiprows=1)

array([[42., 88., 62.],
       [81., 53., 89.],
       [37., 48., 87.],
       [89., 53., 67.],
       [94., 88., 60.],
       [13., 29., 26.]])

In [16]:
data=np.random.randint(0,10,(10,10))

In [17]:
np.save("array.npy",data)

In [10]:
np.load("/content/array.npy")

array([[8, 5, 6, 5, 6, 9, 0, 5, 0, 9],
       [7, 7, 4, 4, 6, 4, 2, 1, 4, 9],
       [3, 8, 2, 2, 3, 6, 9, 5, 5, 5],
       [0, 7, 2, 1, 5, 7, 8, 8, 9, 2],
       [5, 5, 6, 0, 0, 6, 8, 7, 8, 2],
       [0, 3, 5, 7, 9, 2, 0, 7, 8, 0],
       [7, 9, 2, 0, 8, 0, 8, 9, 4, 4],
       [9, 4, 7, 6, 6, 8, 5, 9, 8, 9],
       [9, 9, 7, 3, 8, 4, 3, 8, 2, 2],
       [4, 9, 1, 0, 8, 8, 5, 0, 8, 7]])

In [21]:
arr=np.fromstring("1 2 3 4 5",sep=" ")
arr

array([1., 2., 3., 4., 5.])

In [26]:
txt=open("/content/sample.txt")
print(txt.read())

sample text
sample text
sample text
sample text
sample text



In [30]:
txt.seek(0)
print(txt.read())


abc
abc
abc
abc
abc
abc
abc


In [34]:
txt.seek(0)
txt.read().splitlines()

['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']

In [37]:
with open("/content/sample.txt","w") as file:
  file.write("first code")

In [42]:
with open("/content/sample.txt","r") as file:
  j=file.read()
  print(j)

first code


In [46]:
with open("/content/sample.txt","a") as file:
  file.write("first code \n")
  file.write("second code \n")
  file.write("third code \n")

In [47]:
with open("/content/sample.txt","r") as file:
  l=file.read()
  print(l)

first code 
second code 
third code 
first code 
second code 
third code 



In [59]:
with open("/content/sample.txt","r+") as file:
  text=file.read()
  file.seek(0)
  file.write("parrot" +text)

In [58]:
with open("/content/sample.txt","r") as file:
  k=file.read()
  print(k)

sparrotsample


